config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "nutrients#index"
  resources :nutrients
  resources :users
  resources :calendars
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
	<div class="inner">
  	<!-- 左側 -->
		<div id="info" class="grid">
			<!-- ロゴ -->
			<div class="logo">
        <%= link_to 'EatHealthy!!!!', root_path %>
			</div>
			<!-- / ロゴ -->
			<!-- 電話番号+受付時間 -->
			<div class="info">
				<p class="tel">食べて健康!!</p>
			</div>
			<!-- / 電話番号+受付時間 -->
		</div>  
		<!-- / 左側 -->
		<!-- 右側 ナビゲーション -->
		<ul class="footnav">
        <li><%= link_to 'トップページ', root_path %></li>
        <li><%= link_to '食材登録', new_nutrient_path %></li>
				<li><%#= link_to '食材修正', new_nutrient_path %></li>
				<li><%= link_to 'プロフィール編集', new_nutrient_path %></li>
				<% if user_signed_in? %>
				<li><%= link_to 'カレンダー', calendars_path %></li>
				<li><%= link_to "マイページ", user_path(current_user) %></li>
				<% end %>
		</ul>
		<!-- / 右側 ナビゲーション -->
	</div>
  	<address>Copyright(c) 2013 Sample Inc. All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank" rel="nofollow">http://f-tpl.com</a></address>
</footer>
	<!-- / フッター -->

app/views/shared/_header.html.erb
<header id="header">
	<br>
  <!-- ロゴ -->
	<div class="logo">
        <%= link_to 'EatHealthy!!!!', root_path %>
				<p class="logo-sub">健康的な食事をサポート</p>
	</div>

	<!-- / ロゴ -->
	<!-- 電話番号+受付時間 -->
	<% if user_signed_in?%>
  <div class="info">
		<p class="tel"><%= link_to "#{current_user.name} ", user_path(current_user) %> さん</p>
	</div>
  <% end %>
	<!-- / 電話番号+受付時間 -->
</header>

<!-- メインナビゲーション -->
<nav id="mainNav">
	<div class="inner">
  	<a class="menu" id="menu"><span>MENU</span></a>
		<div class="panel">   
    	<ul>
        <li><%= link_to 'トップページ', root_path %></li>
        <li><%= link_to '食材登録', new_nutrient_path %></li>
				<li><%= link_to 'カレンダー', calendars_path %></li>
				<% if user_signed_in?%>
					<li><%= link_to 'プロフィール編集', edit_user_path(current_user) %></li>
          <li><%= link_to "マイページ", user_path(current_user) %></li>
          <li class="last"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
	  			<li class="last"><%= link_to '新規登録', new_user_registration_path %></li>
        <% end %>
      </ul>   
    </div>
	</div> 
</nav>
<!-- / メインナビゲーション -->